spring.application.name=api-gateway
server.port=8080
spring:
  cloud:
     gateway:
        routes:
          -id=auth-service
           uri=lb://auth-service
           predicates:
             - Path=/auth/**
             
          -id=cart-service
           uri=lb://cart-service
           predicates:
             - Path=/electric-store/cart/** 
               
          -id=category-service
           uri=lb://category-service
           predicates:
             - Path=/electric-store/api/category/** 
             
          -id=product-service
           uri=lb://product-service
           predicates:
             - Path=/electric-store/api/product/** 
             
          -id=user-service
           uri=lb://user-service
           predicates:
             - Path=/users/**          